<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Raffle extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'description',
        'winner',
        'first_prize',
        'second_prize',
        'third_prize',
        'draw_date',
        'draw_location',
        'show_draw_date',
        'request_email_in_purchase',
        'auto_number_selection',
        'max_auto_numbers',
        'disable_auto_payment_completion',
        'bank_account_id',
        'disable_manual_number_selection',
        'show_remaining_numbers',
        'price_per_number',
        'show_price_on_homepage',
        'promotions',
        'sales_goal_percentage',
        'pending_reservation_limit_value',
        'pending_reservation_limit_time',
        'min_number_purchase',
        'max_number_purchase',
        'show_top_3_in_draw_page',
        'total_numbers',
        'number_range_from',
        'number_range_to',
        'main_photo',
        'auto_buy_option_one',
        'auto_buy_option_two',
        'auto_buy_option_three',
        'video',
        'state',
        'city',
        'reference_code',
        'bonus_link',
        'winner_number_1',
        'winner_number_2',
        'winner_number_3',
        'winner_number_4',
        'winner_number_5',
        'winner_number_6',
        'winner_number_7',
        'sorted',

        'premier_number_1',
        'premier_number_2',
        'premier_number_3',
        'premier_number_4',
        'premier_number_5',
        'premier_number_6',
        'premier_number_7',
        'premier_number_8',
        'premier_number_9',
        'premier_number_10',
        'premier_number_11',
        'premier_number_12',
        'premier_number_13',
        'premier_number_14',
        'premier_number_15',
        'premier_number_16',
        'premier_number_17',
        'premier_number_18',
        'premier_number_19',
        'premier_number_20',
        'premier_number_21',
        'premier_number_22',
        'premier_number_23',
        'premier_number_24',
        'premier_number_25',
        'premier_number_26',
        'premier_number_27',
        'premier_number_28',
        'premier_number_29',
        'premier_number_30',

        'show_premier_awards',
        'show_winner_premier_awards',

        'draw_hour',
        'draw_location',
        'additional_draw_info',
        'publication_date',
        'publication_hour',
        'fourth_prize',
        'fifth_prize',
        'sixth_prize',
        'seventh_prize',
        'eighth_prize',
        'ninth_prize',
        'add_top_3_buyers',
        'first_top_buyer_prize',
        'second_top_buyer_prize',
        'third_top_buyer_prize',
        'quantity_personalized_tickets',
        'show_sales_percentage_bar',
        'choice_tickets',
        'show_numbers_on_payment',
        'allow_affiliate',
        'commission_amount',
        'ticket_promotion_value_unit',
        'quantity_tickets_first_promotional_package',
        'total_value_first_promotional_package',
        'quantity_tickets_second_promotional_package',
        'total_value_second_promotional_package',
        'quantity_tickets_third_promotional_package',
        'total_value_third_promotional_package',
        'quantity_tickets_fourth_promotional_package',
        'total_value_fourth_promotional_package',
        'winner_number_8',
        'winner_number_9',
        'status',

        'premier_number_award_1',
        'premier_number_award_2',
        'premier_number_award_3',
        'premier_number_award_4',
        'premier_number_award_5',
        'premier_number_award_6',
        'premier_number_award_7',
        'premier_number_award_8',
        'premier_number_award_9',
        'premier_number_award_10',
        'premier_number_award_11',
        'premier_number_award_12',
        'premier_number_award_13',
        'premier_number_award_14',
        'premier_number_award_15',
        'premier_number_award_16',
        'premier_number_award_17',
        'premier_number_award_18',
        'premier_number_award_19',
        'premier_number_award_20',
        'premier_number_award_21',
        'premier_number_award_22',
        'premier_number_award_23',
        'premier_number_award_24',
        'premier_number_award_25',
        'premier_number_award_26',
        'premier_number_award_27',
        'premier_number_award_28',
        'premier_number_award_29',
        'premier_number_award_30',

        'premier_number_enabled_1',
        'premier_number_enabled_2',
        'premier_number_enabled_3',
        'premier_number_enabled_4',
        'premier_number_enabled_5',
        'premier_number_enabled_6',
        'premier_number_enabled_7',
        'premier_number_enabled_8',
        'premier_number_enabled_9',
        'premier_number_enabled_10',
        'premier_number_enabled_11',
        'premier_number_enabled_12',
        'premier_number_enabled_13',
        'premier_number_enabled_14',
        'premier_number_enabled_15',
        'premier_number_enabled_16',
        'premier_number_enabled_17',
        'premier_number_enabled_18',
        'premier_number_enabled_19',
        'premier_number_enabled_20',
        'premier_number_enabled_21',
        'premier_number_enabled_22',
        'premier_number_enabled_23',
        'premier_number_enabled_24',
        'premier_number_enabled_25',
        'premier_number_enabled_26',
        'premier_number_enabled_27',
        'premier_number_enabled_28',
        'premier_number_enabled_29',
        'premier_number_enabled_30',

        'premier_number_enable_date_1',
        'premier_number_enable_date_2',
        'premier_number_enable_date_3',
        'premier_number_enable_date_4',
        'premier_number_enable_date_5',
        'premier_number_enable_date_6',
        'premier_number_enable_date_7',
        'premier_number_enable_date_8',
        'premier_number_enable_date_9',
        'premier_number_enable_date_10',
        'premier_number_enable_date_11',
        'premier_number_enable_date_12',
        'premier_number_enable_date_13',
        'premier_number_enable_date_14',
        'premier_number_enable_date_15',
        'premier_number_enable_date_16',
        'premier_number_enable_date_17',
        'premier_number_enable_date_18',
        'premier_number_enable_date_19',
        'premier_number_enable_date_20',
        'premier_number_enable_date_21',
        'premier_number_enable_date_22',
        'premier_number_enable_date_23',
        'premier_number_enable_date_24',
        'premier_number_enable_date_25',
        'premier_number_enable_date_26',
        'premier_number_enable_date_27',
        'premier_number_enable_date_28',
        'premier_number_enable_date_29',
        'premier_number_enable_date_30',

        'auto_buy_option_four',
        'auto_buy_option_five',
        'auto_buy_option_six',
        'auto_buy_highlight',
        'quantity_premier_numbers',

        'susep_process',
        'serie_size',
    ];

    public function numbers()
    {
        return $this->hasMany(Number::class);
    }

    public function invoices()
    {
        return $this->hasMany(Invoice::class);
    }

    public function scopeSearch($query, $search)
    {
        return $query->where('name', 'like', "%$search%");
    }

    public function getTotalNumbers()
    {
        return ($this->quantity_personalized_tickets > $this->total_numbers) ? $this->quantity_personalized_tickets : $this->total_numbers;
    }
}
